name: "CLA Assistant"
on:
  workflow_call:
    inputs:
      repository:
        description: "The repository that the CLA is generated for"
        required: true
        type: string
      version:
        description: "CLA version. Keep default to use organization default."
        default: v1
        type: string
      CLASHA:
        description: "The SHA for the commit, the CLA version is. Keep default to use organization default."
        default: 1a3a56410df569e0672aafd508044da85f194e8b
        type: string
    secrets:
      CLA_ASSISTANT_PAT:
        description: CLA Repository Access Token

permissions:
  actions: write
  contents: read
  pull-requests: write
  statuses: write

jobs:
  CLAAssistant:
    name: "CLA Assistant"
    # Only run CLA assistant within the CTF Pilot organization
    if: github.repository_owner == 'ctfpilot'
    runs-on: ubuntu-latest
    steps:
      - name: "CLA Assistant"
        if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request_target'
        uses: contributor-assistant/github-action@v2.6.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.CLA_ASSISTANT_PAT }}
        with:
          path-to-signatures: "signatures/${{ inputs.repository }}/${{ inputs.version }}/cla.json"
          path-to-document: "https://github.com/ctfpilot/cla/blob/${{ inputs.CLASHA }}/CLA.md"

          # branch should not be protected
          branch: "main"
          allowlist: ""
          lock-pullrequest-aftermerge: false
          use-dco-flag: false

          # Remote CLA repo
          remote-organization-name: "ctfpilot"
          remote-repository-name: "cla"
          create-file-commit-message: "Creating file for storing CLA Signatures"
          signed-commit-message: "$contributorName has signed the CLA in $owner/$repo"
          custom-notsigned-prcomment: 'Thank you for your contribution! Before we can proceed, please sign the Contributor License Agreement (CLA) by replying to this comment with "I have read the CLA Document and I hereby sign the CLA". You can find the CLA document [here](https://github.com/ctfpilot/cla/blob/1a3a56410df569e0672aafd508044da85f194e8b/CLA.md).'
          custom-pr-sign-comment: "I have read the CLA Document and I hereby sign the CLA"
          custom-allsigned-prcomment: "All Contributors have signed the CLA. Thank you for your cooperation!"
